# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0004_auto_20161123_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(max_length=200)),
                ('issued', models.CharField(max_length=200)),
                ('expires', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdb.Client')),
            ],
        ),
    ]
