# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0005_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bdate',
            field=models.DateField(),
        ),
    ]
