# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0007_auto_20161123_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expires',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='issued',
            field=models.DateField(),
        ),
    ]
