# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0008_auto_20161123_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.DateField()),
                ('address', models.DateField()),
                ('shopphone', models.DateField()),
            ],
        ),
    ]
