# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0009_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efname', models.CharField(max_length=200)),
                ('elname', models.CharField(max_length=200)),
                ('egender', models.CharField(choices=[('FEMALE', 'female'), ('MALE', 'male')], max_length=6)),
                ('ebdate', models.DateField()),
                ('ephone', models.CharField(max_length=200)),
                ('eemail', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopphone',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdb.Shop'),
        ),
    ]
