# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0010_auto_20161123_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdb.Client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdb.Employee')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdb.Shop')),
            ],
        ),
    ]
