# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0011_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productattribute', models.ManyToManyField(to='shopdb.ProductAttribute')),
            ],
        ),
    ]
