# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0013_auto_20161127_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basketno',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
