# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0016_auto_20161127_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='productattribute',
            new_name='product',
        ),
        migrations.AddField(
            model_name='basket',
            name='client',
            field=models.ManyToManyField(to='shopdb.Client'),
        ),
    ]
