# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0017_auto_20161127_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='client',
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
