# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0018_auto_20161127_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='client',
            field=models.ManyToManyField(to='shopdb.Client'),
        ),
    ]
