# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0019_basket_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='id',
        ),
        migrations.AddField(
            model_name='basket',
            name='unit_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
