# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0021_auto_20161127_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='cart',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
