# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0023_auto_20161127_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.CharField(max_length=200)),
                ('client', models.ManyToManyField(to='shopdb.Client')),
                ('product', models.ManyToManyField(to='shopdb.Product')),
            ],
        ),
    ]
