# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0027_auto_20161213_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='client',
        ),
    ]
