# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdb', '0028_remove_basket_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='client',
            field=models.ManyToManyField(to='shopdb.Client'),
        ),
    ]
